---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  - Пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Корзина хранится в сессии браузера.
implicit:
  - При открытии подробного описания товара и нажатии на фото из галереи товара должно открываться увеличенное фото товара.
  - При нажатии на лого интернет-магазина должна открываться главная страница.
  - На сайте должен быть выбор страницы магазина в каталоге товаров.
